### ISSUE TITLE
add user guide info on forecasting ahead of observed data

### ISSUE THREAD

**Issue by ha0ye** [SugiharaLab/rEDM#18]
Some users want to know about forecasting into unknown futures.

**for known input data, can specify NA for observed future state**:
  * use loop with 1-step ahead forecasts to fill in predictions, one at a time
  * use larger tp steps to generate forecast functions for `tp`-step ahead

**Comment by atredennick** [comment]
@ha0ye Can `rEDM::simplex()` make forecasts of unobserved future states when modeling a univariate (i.e., no input data) time series? I've tried tacking on `NA` to the state vector, but this doesn't seem to work. Thanks!

**Comment by ha0ye** [comment]
Hi @atredennick, are you trying to do a 1-step ahead forecast or a whole series of forecasts to simulate a future trajectory?

If it's the former, you might need some tweaking of the `pred` params, so that there are enough lags to form the state vector to predict from:

```
ts <- c(rnorm(54), NA)
lib <- c(1, 50)   # use points 1-50 to construct model
pred <- c(51, 55) # use points 51-54 to construct state vector, 
                  # predict point 55

out <- simplex(ts, lib = lib, pred = pred, 
               E = 4, stats_only = FALSE)
out$model_output
```

**Comment by atredennick** [comment]
Thank you @ha0ye! That works great. Yes, I am just trying to do 1-step ahead forecasts at the moment. Ideally, I'd actually just like to just simulate time-series from the fitted model from, say, different initial conditions. Looks like the best way to do that with `rEDM` is to iteratively forecast. But maybe I'm wrong.

Thanks again.

**Comment by ha0ye** [comment]
Great! Yeah, the code is built to maintain similar operations as legacy code, so it doesn't function in quite the same way as other kinds of models in R, where the model object can be used directly to iteratively make forecasts. You'll probably want to write some kind of wrapper function to make that easier.
