### ISSUE TITLE
simplex outputting null predictions in model_output

### ISSUE THREAD

**Issue by elligottmc** [SugiharaLab/rEDM#22]
I am following the User Guide and set stats_only parameter to FALSE to review the actual predictions.  They appear to be null.  I am reproducing the same values for rho, etc. and the same plots as in the Guide but predictions appear to be null.

> head(simplex_output[[1]]$model_output)
  time        obs pred pred_var
1    2 -0.6012986  NaN      NaN
2    3  0.7998003  NaN      NaN
3    4 -0.7944096  NaN      NaN
4    5  0.7979992  NaN      NaN
5    6 -0.8195405  NaN      NaN
6    7  0.8051964  NaN      NaN

Thx,

Shane

**Comment by ha0ye** [comment]
What are your input settings? Right now, the output doesn't trim to just the region of the time series being predicted, so it can include points just used for training the model.
