### ISSUE TITLE
feeding block_lnlp output into compute_stats

### ISSUE THREAD

**Issue by nonlinearnature** [SugiharaLab/rEDM#30]
Currently, if you feed a .$model_output data.frame from block_lnlp into compute_stats, it does not know what to do. One issue is that they mix nomenclature. Block_lnlp gives columns "obs" and "pred", but compute_stats expected "observed" and "predicted".

**Comment by ha0ye** [comment]
Do you want to just change the names of the columns in `model_output` data.frames?

**Comment by nonlinearnature** [comment]
Changing the expected inputs for compute_stats would break less of my personal code. Are there other places in the package where this nomenclature is relevant? I can't think of any at the moment.
