### ISSUE TITLE
multiple simultaneous targets

### ISSUE THREAD

**Issue by ha0ye** [SugiharaLab/rEDM#31]
Often times, we may want to compute the predictions to multiple target variables at the same time, e.g. for block_lnlp to a whole set of state variables, or CCM to a set of plausible causal variables.

On the algorithm side, this is straightforward, as both simplex and s-map just need some loops added in, as in the `dev` branch.

One issue is that some of the checking on valid vectors for indexing depends on the target variable. If the target variables have different gaps or missing values, this becomes problematic (and is why `dev` hasn't been merged back into `master`).

One solution is to add a prior check on valid vectors for all targets before running and stop if it doesn't pass.

**Comment by shaypal5** [comment]
I'll use this issue to ask a related question: When using the CCM method, and given a system with more than two variables, if I want to infer all possible causal links in the system (so `n^2` potential links for a system with `n` variables), do I just call the CCM method with every possible ordered pair Xi and Xj given in turn to the `lib_column` and `target_column` parameters?

**Comment by shaypal5** [comment]
Why was this closed? Was this documentation gap addressed?
My question, at least, was never answered...

**Comment by SoftwareLiteracy** [comment]
This was closed as a part of cleanup of github.  It seemed to be old, and, not with a current thread.  Apologies for the oversight. 

The question of cross mapping N variables is as you describe.  Although, CCM will generate N^2 tables of prediction skill vs. library size.  That is perhaps not very helpful.  What is often done is to compute a single CCM value at maximum library size, effectively ignoring the 'convergence' aspect of CCM.  You are then doing cross mapping using Simplex at a single library size.  In fact, this can be done using Simplex directly with the columns and target set appropriately to search the N^2 variable space.

**Comment by shaypal5** [comment]
Thank you for taking the time to answer me! :)
