### ISSUE TITLE
Multidimensional time series

### ISSUE THREAD

**Issue by ghost** [SugiharaLab/rEDM#32]
Often times you have multiple observable variables.

How do you construct an attractor from a delayed embedding when you have multiple variables? It is not obvious how a delayed embedding could be constructed.

The naive approach where you have some n variables would require an xn embedding where x is the number of lags.

**Comment by ha0ye** [comment]
If there are more possible variables than needed for embedding, then any combination is generically valid (though not practically so). Please check out the section "Generalized Takens’s Theorem" and related references in the tutorial vignette.
