### ISSUE TITLE
Add ORCID for contributors

### ISSUE THREAD

**Issue by ha0ye** [SugiharaLab/rEDM#36]
Hi @caijun, @yairdaon, @andrew-edwards, @Ironholds,

I'm adding ORCIDs for authors and contributors. I wasn't able to uniquely identify what yours are, so if you'd like me to include this for you, please let me know in this thread, or submit a PR to add this to `DESCRIPTION`.

Thanks!

**Comment by andrew-edwards** [comment]
Thanks Hao. Mine is:

0000-0003-2749-8198

**Comment by caijun** [comment]
Thanks @ha0ye My ORCID is 0000-0001-9495-1226.
