### ISSUE TITLE
rEDM not available in CRAN

### ISSUE THREAD

**Issue by desertnaut** [SugiharaLab/rEDM#39]
As of Jan 16 2020, it seems that the package is no longer available in CRAN:

https://cloud.r-project.org/web/packages/rEDM/index.html

which means that the package cannot currently be installed with `install.packages("rEDM")`.
Any ideas or plans for remedying this?
I initially reported this in the [other rEDM repo](https://github.com/ha0ye/rEDM/issues/16), but I was redirected here.

**Comment by giancarlo-bonotto** [comment]
I would like to emphasize this issue, as I am also trying to use rEDM and that same issue happens. Moreover, the command **install.packages("devtools")** and 
**devtools::install_github("SugiharaLab/rEDM")** also do not work... 

Thanks for your attention.

**Comment by SoftwareLiteracy** [comment]
CRAN has been updated.
