### ISSUE TITLE
rEDM does NOT work on WindowsOS

### ISSUE THREAD

**Issue by KAMATAN5708** [SugiharaLab/rEDM#40]
I installed rEDM to WindowsOS. When the library was called by the command "library(rEDM)", the  R  program hanged up.

**Comment by SoftwareLiteracy** [comment]
Please try to install version 1.5 from CRAN.

**Comment by SoftwareLiteracy** [comment]
CRAN has been updated. Note that old release (r-oldrel-windows-ix86+x86_64) is no longer supported by R.
