### ISSUE TITLE
I can not library the "rEDM"

### ISSUE THREAD

**Issue by HanDing-water** [SugiharaLab/rEDM#42]
WHEN I LIBRARY THE "rEDM",THE R ALWAYS HAVE NO RESPONSE AND CANNOT EXECUTE ANY COMMAND.

**Comment by SoftwareLiteracy** [comment]
Please provide the platform information, R version and rEDM version. 

Note that old R release on windows (r-oldrel-windows-ix86+x86_64) is no longer supported by R.

**Comment by tigerwang1998** [comment]
I have encountered the same problem. My R version is 4.1.2 and rEDM version is 1.9.3. After waiting for more than 2 hours, the library ended. I would be grateful if you could reply to my question.
