### ISSUE TITLE
setting knn < E+1

### ISSUE THREAD

**Issue by jeffhoul** [SugiharaLab/rEDM#46]
Hi George and all, we are running SImplex in rEDM and trying to set knn < E+1 - we used to be able to do this but using a newer version of rEDM (or maybe R) it looks like we no longer can.  Now, we get an error message

"Error in RtoCpp_Simplex(pathIn, dataFile, dataFrame, pathOut, predictFile,  :   Parameters::Validate(): Simplex knn of 1 is less than E+1 = 2"

Is this intentional?  Are you trying to prevent knn from ever being less than E+!?  And if so, why?  Thanks for any help you can be.  Best, Jeff Houlahan

**Comment by nonlinearnature** [comment]
Hi Jeff--I will look into removing that restriction. Thanks for pointing it out!
Ethan

**Comment by jeffhoul** [comment]
That's great, Ethan.  Thanks a lot. Best, Jeff H

________________________________

**Comment by nonlinearnature** [comment]
Fixed, thanks to Joseph! Re-install with the new push, 1.8.1 and you should be fine to specify any knn >= 1!

**Comment by jeffhoul** [comment]
Thanks Ethan.  I really appreciate how quickly you jumped on this.  Best, Jeff

________________________________

**Comment by nonlinearnature** [comment]
All kudos to Joseph!

**Comment by SoftwareLiteracy** [comment]
fyi: here's an installable image: [rEDM_1.8.1.tar.gz](https://drive.google.com/file/d/1KrCo5vtc-MlncMHUBkrtNWI3KKAyeqEJ/view?usp=sharing)

**Comment by jeffhoul** [comment]
Thanks very much for this.  Best, Jeff H

________________________________
