### ISSUE TITLE
dgelss failed

### ISSUE THREAD

**Issue by roblesmudan** [SugiharaLab/rEDM#47]
Hi, I'm having a problem while executing PredictNonLinear (using the tutorial with my data). Maybe it is too obvious but I'm very new to R.

My data looks something like this:
> head(datos,2)
  Year Month   Area     Date
1 2000     1     NA ene 2000
2 2000     2 24.012 feb 2000

Error section:

> E = 3
> 
> rho_theta_e3 =PredictNonlinear(dataFrame = datos, columns = "Area",target = "Area", lib = "2 228", pred = "2 228", E = E)

Error in RtoCpp_PredictNonlinear(pathIn, dataFile, dataFrame, pathOut,  : 
  Lapack_SVD(): dgelss failed.

**Comment by nonlinearnature** [comment]
Can you try rerunning with a data frame that's just 1 column with a row index and 1 column with "Area"?

**Comment by roblesmudan** [comment]
Sure!
Assuming I understand you correctly, this is what I get.

New Data frame
> head(df,2)
  ID   Area
1  1     NA
2  2 24.012

Output:

> rho_theta_e3 =PredictNonlinear(dataFrame = df, columns = "Area",target = "Area", lib = "2 228", pred = "2 228", E = E)

Error in RtoCpp_PredictNonlinear(pathIn, dataFile, dataFrame, pathOut,  : 
  Lapack_SVD(): dgelss failed.

**Comment by SoftwareLiteracy** [comment]
What is the rEDM and R version information?

I believe the LAPACK solver does not handle NAs.  Since `PredictNonlinear` is a wrapper for `SMap`:

```
> sessionInfo()
R version 4.0.4 (2021-02-15)
other attached packages:
[1] rEDM_1.8.1

> library(rEDM)
> df = data.frame( time = 1:10, x = rnorm( 10 ), y = rnorm( 10 ) )
> head( df, 2 )
   time        x       y
1     1 -0.34302  0.1966
2     2 -1.51635 -0.3802

> sm = SMap( dataFrame = df, lib = "1 10", pred = "1 5", E = 2, theta = 0.5, columns = 'x', target = 'y' )
> names( sm )
[1] "predictions"  "coefficients"

> df $ x[1] = NA
> head( df, 2 )
  time      x       y
1    1     NA  0.1966
2    2 -1.516 -0.3802

> sm = SMap( dataFrame = df, lib = "1 10", pred = "1 5", E = 2, theta = 0.5, columns = 'x', target = 'y' )
Error in RtoCpp_SMap(pathIn, dataFile, dataFrame, pathOut, predictFile,  : 
  Lapack_SVD(): dgelss failed.
```

**Comment by roblesmudan** [comment]
Thank you! :D

Yep, you are absolutely right, it was related to the NaN. I thought that ignoring it with lib and pred was enough. 

I'm just gonna add my problem and the solution in case anyone encounters the same issue. 

Case 1 :  Ignoring NaN with lib and pred arguments.
> head(df,2)
  ID   Area
1  1     NA
2  2 24.012
> rho_theta_e3 =PredictNonlinear(dataFrame = df, columns = "Area",target = "Area", lib = "1 227", pred = "1 227", E = E)
Error in RtoCpp_PredictNonlinear(pathIn, dataFile, dataFrame, pathOut,  : 
  Lapack_SVD(): dgelss failed.

Case 2 : Removing the NaN value. 
> df2 <- df[2:228,]
> head(df2,2)
  ID   Area
2  2 24.012
3  3 39.190
> rho_theta_e3 =PredictNonlinear(dataFrame = df2, columns = "Area",target = "Area", lib = "1 227", pred = "1 227", E = E)
It works!

Thank you for creating, developing and maintaining rEDM and pyEDM :+1:

**Comment by schatterje22** [comment]
Hi, I am using rEDM package in R but there are major gaps in our data. Clearly, if there are NAs then the rEDM functions (e.g., EmbedDimension, PredictNonLinear, CCM) are not running or showing errors in prediction. 

1)
ccm_out_tau <- CCM(dataFrame = df3, E = 6, Tp = 0, columns = "ET", target = "PET", tau = tau,
                                              libSizes = c(10, 962, 5), sample = 100, replacement = F, showPlot = TRUE)      

WARNING: ComputeError(): nan predictions found error not computed

2)
theta.rho1 <- PredictNonlinear( dataFrame=df3, E=6,lib="1 962",theta = "",
                                     pred="1 962", columns="ET", target="ET", showPlot = TRUE)

Error in RtoCpp_PredictNonlinear(pathIn, dataFile, dataFrame, pathOut, :
Lapack_SVD(): dgelss failed.


I'm wondering if you can help me solve this issue.
Thank you.
