### ISSUE TITLE
When should different surrogate generation functions be used?

### ISSUE THREAD

**Issue by shivanp** [SugiharaLab/rEDM#50]
I have an ecological dataset with a high level of seasonality, and I was wondering whether it would be better to use the 'make_surrogate_twin' or the 'make_surrogate_seasonal' method within make_surrogate_data? In the rEDM apple thrips example (https://ha0ye.github.io/rEDM/articles/rEDM.html#edm-examples), the seasonal option is picked to generate surrogates, whereas in Ushio (2018), phase lock twin surrogate has been used.

Are there specific advantages and disadvantages to each of these algorithms, particularly in ecological food-web settings? For example, is one better for identifying inter-specie interactions, and another better for identifying causal interactions between species and environmental variables?

Many thanks

**Comment by SoftwareLiteracy** [comment]
As this question has been languishing without a response from the community, and, this forum is primarily for code issues on this git respository, I'll close it with my naive comments.

I agree that there are specific advantages and disadvantages to each of these algorithms. Perhaps another perspective is that each method was specifically designed to address a specific pattern(s) of presumed stochasticity. 

Please note that the current code (1.9.2) pyEDM and rEDM on this git support three methods:
1. random_shuffle
2. ebisuzaki
3. seasonal

The documentation describes each of these algoroithms. 

The example link you cite is from the git of Hao Ye.  His version may implement other options.
