### ISSUE TITLE
Causality detection in the short time series

### ISSUE THREAD

**Issue by Spatial-R** [SugiharaLab/rEDM#6]
Hello, thanks for the rEDM package, which provides a very convenience way to find the cross-interaction between some infectious diseases . However, when used the rEDM package, i came across  some problems and hope you can help me. 

**Assuming that there are three dynamic process named A, B, C (C depends on A), and i want to test whether there is a synergistic effect on C when A and B coexist**.

There are several weakness in my dataset.  Firstly, my dataset is only with 104 week. Secondly, most of B and C have zero value. The dataset is [here](https://github.com/Spatial-R/Dynamic-Model-for-Infectious-Disease/tree/master/CCM)

**Comment by ha0ye** [comment]
The rEDM Github issues page isn't the appropriate venue if you're having analysis questions, so I'm going to close this, but please feel to email me [hye AT ucsd ... edu].
