### ISSUE TITLE
Question: which version of rEDM had the syntax ...$stats$rho$rho to extract the rho from a block_lnlp call?

### ISSUE THREAD

**Issue by TraxOnDaRocks** [SugiharaLab/rEDM#65]
Hello, I'm very sorry to bother with such a trivial question but I've been trying to figure this out for a while without success.
In April and May 2022 I used rEDM for a research project. For unforeseen reasons I now have to re-run some of the analyses from this project. I want to ensure that I use the same version of rEDM that I initially used back in 2022.

Here's what my code looks like:

```
simplex_output = block_lnlp(df, lib = c(1, floor(endPoint / 2)), pred = c(floor(endPoint/2)+1, endPoint), target_column = colname, 
                            tp = forecast_time, stats_only = FALSE, first_column_time = FALSE, silent = TRUE)

simplex_output_rho = simplex_output$stats$rho$rho
```

Considering when I wrote my code, I would presume that I used version 1.2.2 or 1.2.3, but in these versions (and later ones) the call to block_lnlp() does not work. I've tried earlier versions too, but while block_lnlp() works in these, the $stats$rho$rho syntax does not. 
So my question is this: what version of rEDM could I possibly have used for the above code to work?

Thanks in advance and again, sorry to bother.

**Comment by SoftwareLiteracy** [comment]
Please see [Issue #64 ](https://github.com/SugiharaLab/rEDM/issues/64).

Although calls to `block_lnlp` should work until [rEDM_1.14.3.tar.gz](https://cran.r-project.org/src/contrib/Archive/rEDM/rEDM_1.14.3.tar.gz)	2023-07-07, this is not recommended with the 1.X code.

**Comment by TraxOnDaRocks** [comment]
@SoftwareLiteracy Thank you for your response and sorry for taking so long to get back.
Are you by any chance aware of a version of rEDM where the syntax 'simplex_output$stats$rho$rho' would have worked in my use case? I am trying to ensure that I am using the same version of the package that I was using back in 2022 (I regret not taking note of it back then).

**Comment by SoftwareLiteracy** [comment]
Hi again. 

I looked at the code for the 2022 versions 1.10-1.13, and they all have the same return for `block_lnlp(stats_only=FALSE)` which is to return a named list with items `stats` and `model_output` where `stats` is a data.frame with `rho` from a named list. So it looks like it could have been any of those versions.

**Comment by TraxOnDaRocks** [comment]
@SoftwareLiteracy thank you so much! no idea how i missed that.
