### ISSUE TITLE
Choosing values for E and D in the Multiview function

### ISSUE THREAD

**Issue by kkhader** [SugiharaLab/rEDM#68]
I have a question about how to choose the values for E and D in the Multiview function. It seems like the approach should be similar to that in identifying the optimal value of E in a single view (Simplex()) application where forecast skill is evaluated across a range of candidate values for E and then typically the embedding dimension that corresponds with the best forecast skill is selected for E. 

In the Multiview setting (or even multidimensional applications generally), the 'optimal' selection for E and D doesn't seem to be described anywhere. It isn't obvious that the choice of E from a 1-dimensional application should carry forward to a multidimensional application. Therefore, it seems like one should evaluate forecast skill across a range of candidate values of both E and D, and then select E and D that have the best forecast skill (and then the specific best fit can be determined by looking at the View output from the Multiview function. But as far as I can tell, this isn't described anywhere. Can you help clarify this process for me?

Thanks!

Karim

**Comment by SoftwareLiteracy** [comment]
Hi Karim, 

This is an interesting question that is rather deep in implications.

Your suggested approach of maximal predictability to guide parameter selection is reasonable. I'll offer a few comments based on my understanding that will hopefully be useful.

EDM is predicated on the notion of a stable, invariant state space (manifold, attractor...) which encapsulate the dynamics: one presumes completely.  In the univariate time series case the optimai time-delay embedding dimension is presumed to achieve this. 

However, the state space embedding with optimal predictability can be influenced by both the value of E and tau.  One can see the combination of E & tau capture different timescales in the embedding (state space) vectors, as such, it is common to evaluate both E & tau when selecting an optimal embedding. Once this is done these values are used in subsequent analysis such as cross mapping or s-map. 

Here, one has transformed a univariate (1D) vector into an E-dimensional vector. In this sense, the system is actually E-dimensional, a multivariate system, thus the idea of multidimensional system is implicit in nonlinear dynamics and EDM.  In fact, the multivariate embedding is not restricted to time-delay embedding: [Generalized Theorems for Nonlinear State Space Reconstruction](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0018295) 

Multiview brings these ideas together, that observation functions, perhaps composed of time delay embedding of individual observation functions, can best represent the system dynamics.  In Multiview the parameter D represents the overall system dimension, while E represents the time-delay embedding dimension of each multivariate. If E = 1 then each multivariate is the data vector itself with no additional time delay components.

When one has explicit multidimensional observation functions, how does one estimate the dimensionality of the system?  I don't think there is a general answer.  My approach has been to assess the optimal univariate time delay embedding of the response variable as the system dimension D, then use a range of time-delay embedding dimensions E & tau to generate multiple candidate observables for the D dimensional system. 

It also bears mention that the `excludeTarget` parameter is important in that it controls whether or not the target variable is included in the multiviews.
